First mr
kifbell/nn-from-scratch pull request #1
Opened 2024-04-20 20:19 UTC by kifbell

2024-04-21 15:01 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

Порядок методов в cpp файле должен быть точно такой же как в h файле!

Добавь clang-format и clang-tidy

Избавься от виртуальных функций и используй стирающие типы. Либо возьми у меня AnyObject или возьми библиотеку folly и используй ее poly объекты.

НИКОГДА НЕ используй shared_ptr на НЕ константные объекты.

Следи за тем, чтобы НЕ копировать контейнеры, используй std::move везде, где ты передаешь данное и больше его не используешь.

Проставь assert-ы на preconditions в каждой функции, где есть какие-то условия на аргументы. Не проверяй через assert-ы логику поведения программы вроде того зануляется градиент или нет. Этот механизм НЕ для этого. Логикой программы должен control flow.

2024-04-21 15:01 UTC, DimaTrushin commented on CMakeLists.txt
> +        SoftmaxLayer.h
Не надо включать h файлы в add_executable. Сюда надо добавлять лишь cpp файлы, h файлы должны только инклудиться в cpp файлы.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.cpp
Убрать пустые cpp файлы.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +
Не пиши в global namespace, заведи пространство имен для проекта и все пиши в него.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    std::vector<std::vector<double>> features; // Store features in a 2D vector
Никогда не  используй вектор векторов. Это сильно бьет по производительности. Либо напиши свой контейнер содержащий один вектор и имеющий оператор operator()(int row, int column). Либо используй Eigen::MatrixXd или Eigen::Array. Они как раз дают возможность работать с двойными массивами.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    std::vector<int> labels; // Store labels in a vector
Убрать комментарии. У тебя и так понятно, что ты тут хранишь вектор меток.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    std::vector<int> labels; // Store labels in a vector
Переменные класса являются глобальными ресурсами для методов класса. Потому нужен механизм отличать их от локальных переменных методов класса. Для этого лучше добавлять либо _ в конце имени, либо m_ в начале, либо что-то подобное.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    DataHandler() {}
Дефолтный конструктор пишется не так. Надо писать
```cpp
DataHandler() = default;
```

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    void readData(const std::string& filename) {
Почему нешаблонный метод объявлен НЕ в cpp файле?

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +        file.close();
Не надо закрывать файловые потоки. Они и так закроются деструктором.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +                parsedRow.push_back(stod(cell)); // Convert string to integer
Не пиши комментарии. Их не читают программисты и их не понимают компиляторы. Если хочешь функцию с нормальным названием, то сделай приватную статическую функцию внутри класса с нормальным названием, например
```cpp
static std::string IntToString(int value) {
  return stod(value);
}
```
И потом используй эту функцию тут
```cpp
parsedRow.push_back(IntToString(cell));
```
И не надо будет писать комментарии.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +        getline(file, line); // skip fist line w/ the names of the columns
Вместо комментария заведи функцию с таким названием
```cpp
static void skipFirstLine(std::ifstream& file) {
  std::string line;
  getline(file, line);
}
```
И  тогда тут не надо будет писать такие вещи.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +        std::string line, cell;
1) Не объявляй переменные заранее. Например cell тебе не нужна до 29 строки.
2) Не объявляей переменные через запятую.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +            while (getline(lineStream, cell, ',')) {
Цикл в цикле обычно говорит о проблемах с дизайном. Это скорее всего какая-то подфункция. В целом сложно понять, что у тебя тут происходит.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +            std::stringstream lineStream(line);
Я бы в целом ожидал следующую структуру цикла
```cpp
std::vector<double> row = parseRow(line);
features.push_back(std::move(row));
```
И все. Вся возьня по парсингу строки скрыта от пользователя во вспомогательной функции. Старайся переменные инициализировать при объявлении. Очень редко, когда так не получается.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +            features.push_back(parsedRow);
Здесь у тебя происходит лишнее копирование. Надо писать
```cpp
features.push_back(std::move(parsedRow));
```
В целом следи за тем, чтобы никогда не копировать контейнеры. Это всегда потенциально дорого.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    std::pair<std::vector<int>, std::vector<std::vector<double>>> getRandomBatch(int batchSize) {
1) Не используй std::pair, потому что пользователю не понятно, что значат first и second. Заведи struct с нужным именем и нужными названиями полей. И тогда пользователь сможет по нормальным названиям обращаться к элементам структуры.
2) Не используй длинные сырые типы. Заведи юзинги для сложных типов, чтобы вот не было такой лапши. И если ты потом захочешь изменить тип, например вместо вектора векторов сделать Eigen::Array, то у тебя придется везде вносить эти изменения. Это как магические константы, только на уровне типов.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +    std::pair<std::vector<int>, std::vector<std::vector<double>>> getRandomBatch(int batchSize) {
Почему метод НЕ константный?

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +        std::uniform_int_distribution<> distr(0, labels.size() - 1); // Define the range
1) НИКОГДА НЕ инициализируй нандом случайным числом при исполнении. У тебя получается НЕ тестируемое окружение. Все твои эксперименты будут НЕ воспроизводимыми. Вместо этого надо завернуть весь рандом в отдельный класс и этот класс сделать статической переменной для этого метода. Например.
```cpp
class Random {
public:
  int uniform_int(int a, int b) {
    std::uniform_int_distribution<> distr(a, b);
    return distr(engine_);
  }
private:
  static constexpr int kSeed = 42;
  std::mt19937 engine_{kSeed};
};
```
И после этого ты можешь в этом методе написать
```cpp
??? getRandomBatch(int batchSize) const  {
  static Random rnd;
  ...
  int index = rnd.uniform_int(0, labels.size() - 1);
}
```
Делегируй всю работу по рандому соответствующему классу.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +        }
1) У тебя идет лишнее копирование данных. Кроме того, с таким рандомом, ты не гарантируешь, что ты одни и те же данные не пройдешь дважды или трижды. У тебя может быть перекос в обучении в сторону одних данных или других. Какие-то ты вообще можешь не увидеть.
2) Лучше заведи массив индексов и случайно шафли его и потом обращайся по массиву индексов. И НЕ копируй данные. Предоставляй данные как есть в нужном формате сразу.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +        return {batchLabels, batchFeatures};
Лишнее копирование
```cpp
return {std::move(batchLabels), std::move(batchFeatures)}};
```

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +//int main() {
Зачем тебе git с его поддержкой версий, если ты оставляешь закомментированный код? Убрать. Гит помнит всю историю и хранит весь код. Если нужно поиграться, то создаешь локально тестовую ветку, там играешь, а потом через checkout пикаешь нужные файлы.

2024-04-21 15:01 UTC, DimaTrushin commented on DataHandler.h
> +//int main() {
Никогда НЕ пиши main функцию где-либо кроме main.cpp.

2024-04-21 15:01 UTC, DimaTrushin commented on CMakeLists.txt
После строки 4 добавь
```cpp
set(CMAKE_CXX_STANDARD_REQUIRED True)
```

2024-04-21 15:01 UTC, DimaTrushin commented on CMakeLists.txt
Строки 7 и 8 подразумевают, что у тебя eigen и eigenrand установлены в сурсовой дирректории. У тебя git submodule обеспечивают наличие этих библиотек там?

2024-04-21 15:01 UTC, DimaTrushin commented on CMakeLists.txt
10 Убрать нерелевантные вещи. Ты не используешь CUDA никак.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>      {};
1) Не определяй явно деструктор там, где это не надо.
2) Не ставь ; после определения функций.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>  {
Убери дефолтный конструктор, он тут не нужен.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>  {
Убери в начале ненужное protected

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    virtual Eigen::VectorXd passForward(const Eigen::VectorXd &input) = 0;
Не используй виртуальные методы никогда. Вместо них используй стирающие типы.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    virtual Eigen::VectorXd passForward(const Eigen::VectorXd &input) = 0;
Не используй сырые типы с квалификаторами доступа вроде Eigen::VectorXd. Заведи в приватной части класса
```cpp
using Vector = Eigen::VectorXd;
using Matrix = Eigen::MatrixXd;
```
Если тебе эти типы нужны глобально, то можешь завести глобальные юзинги в одном хедере, а потом инклудь этот хедер всюду. Но не надо использовать такую длинную ботву.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>      ~Layer()
Если есть виртуальные методы, то и деструктор надо делать виртуальным, иначе у тебя память течет. Но лучше использовать стирающие типы. Можно использовать библиотеку folly от facebook и их стирающие типы folly::poly.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>  private:
Если ты пишешь класс, то у него обязательно есть инварианты на данные, а значит эти данные нельзя делать публичными. Закрой все данные и убери их в приватную часть.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>          // Random initialization of weights and biases for demonstration purposes
Питонячий стиль. Конструктор пишется не так
```cpp
LinearLayer(int input_size, int output_size)
  : weights_(Matrix::Random::(output_size, intput_size)),
    bias_(Vector::Random(output_size)) {}
```

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>      ~LinearLayer()
Убрать. Деструктор тут не нужен. Он будет дефолтным.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    std::map<std::string, Eigen::MatrixXd> optimizerState;
Все данные закрыть.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
>          // Random initialization of weights and biases for demonstration purposes
У Eigen есть специальный тип для размеров матриц, называется Eigen::Index. Используй юзинг для него вместо сырого типа int.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    ReLULayer(int size)
Инициализацию всех данных надо делать в списке инициализации.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +        dsigma = Eigen::MatrixXd::Identity(size, size);
Для ReLu и прочих функций активации, тебе надо хранить две функции саму функцию f: R -> R и ее производную f' : R -> R. Для этого заведи std::function<double(double)> и храни две переменные этого типа. В одну помещай выражение для f, в другую выражение для f'.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    ~ReLULayer()
Убрать.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    explicit SigmoidLayer(int size)
А схуя вдруг нигде не было explicit конструктора, а тут внезапно он нарисовался. Сделай все конструкторы с 1 аргументом explicit.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +    virtual ~SigmoidLayer()
Убрать.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.h
> +class SigmoidLayer : public Layer
Сигмоид, Релу и прочие покоординатные функции активации можно хранить в одном классе вида
```cpp
class CwiseActivation {
  using Function = std::function<double(double)>;
public:
  CwiseActivation(Function f0, Function f1) : f0_(std::move(f0)), f1_(std::move(f1)) {}
  double eval0(double x) const {
    return f0_(x);
  }
  double eval1(double x) const {
    return f1_(x);
  }
private:
  Function f0_;
  Function f1_;
};
```
И так же можно сделать набор статических функций, которые строят функции активации.
```cpp
class CwiseActivation {
public:
...
  static CwiseActivation ReLu() {
    return CwiseActivation([](double x){ return x * (x > 0);}, [](double x){ return x > 0;})
  }
private:
};
```
И аналогично под все другие функции. Тогда их можно строить вызовом
```cpp
auto layer = CwiseActivation::ReLu();
```

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    Eigen::MatrixXd originalWeights = this->weights;
Не используй this явно. Просто пиши weights_ и используй _ в конце имени, чтобы понимать, что это переменная класса.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    Eigen::MatrixXd originalWeights = this->weights;
А зачем тебе это копирование тут?

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +           "Weights should have changed after optimization.");
Плохая проверка. Это не вопрос который надо проверять через assert. Дело в том, что ты будешь использовать assert чтобы отлавливать ошибки в коде, а так у тебя программа будет еще падать не из-за ошибок, а потому что обучение идет не как надо. Ты можешь придумать механизм, с помощью которого ты можешь останавливать обучение, если градиент не меняется. И возвращать это значение наверх.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    return u_bar;
Просто верни выражение
```cpp
return weights.transpose() * u;
```
Eigen лучше всего работает, когда ты не делаешь присвоения временных объектов и сразу составляешь большие выражения.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    Eigen::VectorXd originalBiases = this->bias;
И это выглядит как ненужное копирование.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    Eigen::VectorXd u_bar = weights.transpose() * u;  // u * dσ * A
Судя по всему тут нужно использовать originalWeights. Но лучше этот u_bar посчитать до обновления градиентов, а потом вернуть. И тогда не  надо будет делать ненужные копии для весов и баеса.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    dsigma = input.unaryExpr(
А зачем это запоминать? Эта штука нужна только во время бэкпропа. И она считается по входу input, который ты тоже передаешь в backprop.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    dsigma = input.unaryExpr(
Дорого хранить диагональную матрицу в виде квадратной матрицы. Лучше хранить в виде вектора, а потом применение к другому вектору -- это поэлементное умножение векторов.

2024-04-21 15:01 UTC, DimaTrushin commented on Layer.cpp
> +    dsigma = output.unaryExpr(
Если я правильно понимаю, то unaryExpr действует inplace, то есть output при этом у тебя тоже меняется. Проверь это так или нет.

2024-04-21 15:01 UTC, DimaTrushin commented on Optimizer.cpp
>      if (optimizerState.find("velocityWeights") == optimizerState.end())
1) Заведи вместо строк enum class DataType {velocityWeights, velocityBiases}; и т.д.
2) Вместо того, чтобы делать тупой поиск по std::map, может быть стоит завернуть ее в класс, который будет автоматически искать данные и если их нет, то помещать туда нулевую матрицу нужного размера? Но я пока не уверен, что там получится хороший api.

2024-04-21 15:01 UTC, DimaTrushin commented on Optimizer.cpp
> -    std::cout << "MomentumOptimizer update" << std::endl;
Строки с 6 по 10. Обычно входные аргументы передаются либо по константной ссылке, либо по значению, а выходные по указателю. Ты передаешь по ссылке, это не очень хорошо, ну да ладно. Но всегда вначале ставь входные данные, и только потом в самом конце выходные данные, чтобы пользователь хотя бы был в курсе какие приблизительно данные могут поменяться.

Еще сравни два кода
```cpp
optimizer.update(derA, derb, A, b, history);
// и
optimizer.updatre(derA, derb, &A, &b, &history);
```
Во втором случае код тебе явно говорит, что последние три аргумента поменяются. Этот подход использован в scanf и printf.

2024-04-21 15:01 UTC, DimaTrushin commented on Optimizer.h
Убрать виртуальные методы и перейти на стирающие типы. Так как у тебя в интерфейсе всего один метод, то тебе можно обойтись std::function. Тебе надо хранить
```cpp
class Optimizer {
  using History = std::map<HistoryData, Matrix>;
  using Signature = void(const Matrix&, const Vector&, Matrix&, Vector&, History&);
public:
  void update(const Matrix& derA, const Vector& derb, Matrix& A, Vector& b, History& history) const {
    update_(derA, derb, A, b, history);
  }
private:
  std::function<Signature> update_;
};
```
И теперь ты можешь складывать любой оптимизатор сюда. А для этого просто создаешь статическую функцию для нужного оптимизатора.
```cpp
static momentum() {
  return Optimizer(....);
}
```
И потом будешь использовать это так
```cpp
auto opt = Optimizer::momentum();
```
И не надо будет возиться с виртуальными методами и прочей херней.

2024-04-21 15:01 UTC, DimaTrushin commented on SoftmaxLayer.h
> +Eigen::VectorXd SoftmaxLayer::passForward(const Eigen::VectorXd &input)
Это ODR vialation. Это UB. Либо добавляешь inline в начале каждой функции, либо (что сильно лучше) все это переносишь в cpp файл.

2024-04-21 15:01 UTC, DimaTrushin commented on SoftmaxLayer.h
> +    Eigen::VectorXd lastOutput;
Зачем тут lastOutput? Тебе всегда надо знать лишь lastInput. Иначе ты задваиваешь хранение данных.

2024-04-21 15:01 UTC, DimaTrushin commented on SoftmaxLayer.h
> +    {}
Убрать

2024-04-21 15:01 UTC, DimaTrushin commented on SoftmaxLayer.h
> +    }
Нарушение уровня абстракции. Я бы видел этот код так
```cpp
Matrix jacobian = getJacobian(lastOutput);
return jacobian * u;
```

2024-04-21 15:01 UTC, DimaTrushin commented on SoftmaxLayer.h
> +    optimizer; // Suppress unused variable warning if not used
Подавление делается не так. Вместо этого в заголовке функции убери имя аргумента
```cpp
Vector SoftmaxLayer::backprop(Optimizer &, const Vector &u)
```

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
>  class MSELoss
Это должно быть объявлено в отдельном файле Loss.h и уже потом заинклужено куда надо.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
>  class MSELoss
Если вы определяете
- переменные
- функции
- классы
в cpp файле, то все это надо обязательно завернуть в anonymous namespace. Иначе это чревато ошибками линкера.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> -    Eigen::VectorXd pass_forward(const Eigen::VectorXd &input)
Определи нейросеть в отдельном h файле.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
>      {}
Убрать к хуям shared_ptr К ХУЯМ я сказал.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
>      {}
Никогда не принимай контейнеры. Дело в том, что у тебя возможна конвертация типов неявная в этом случае и ты можешь делать потенциально очень дорогие операции. Потому лучше либо принимать прокси view объекты, либо принимать итераторы, либо std::initializer_list (но это только если объекты легкие, а у тебя layers нифига не легкие.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> +int argmax(const Eigen::VectorXd& vec) {
Все функции отсюда и далее до main не включительно. Это какие-то вспомогательные функции, которым тут не место. Выдели h файл с математическими функциями.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> +int argmax(const Eigen::VectorXd& vec) {
У тебя не консистентное оформление, у тебя то фигурная скобка на той же строке, то на новой. Приведи все в порядок. Добавь clang-format и отформатируй с помощью него весь текст.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> +    std::shared_ptr<Layer> layer1 = std::make_shared<LinearLayer>(784, 300);
НИКОГДА НЕ используй shared_ptr. Даже тут unique_ptr тебе бы хватило. НО еще лучше использовать стирающие типы и в этом случае у тебя вообще не надо будет мучить жопу с помощью всякой дичи вроде умных указателей.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> +    std::vector<std::shared_ptr<Layer>> layers = {
Это плохой способ инициализировать вектор вообще говоря. В случае shared_ptr это не так страшно, но тут реально происходит следующее. У тебя сначала справа создается std::initializer_list, а уже потом из него данные копируются в вектор при инициализации. Лучше всегда делать reserve, а потом emplace_back.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
>      // Training loop
Выдели отдельную функцию обучения нейросети и вызывай ее.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> +Eigen::VectorXd calculateMean(const std::vector<Eigen::VectorXd> &vectors)
Я очень рекомендую принимать не вектор от Eigen::VectorXd, а Eigen::MatrixXd. И там использовать colwise операции. Это можно даже сделать с помощью вызова пары функций встроенных.

2024-04-21 15:01 UTC, DimaTrushin commented on main.cpp
> +int main()
Функция main никогда не должна ничего делать сама. Она должна все делегироват другим частям программы и должна предотвращать от утечки ошибок в операционную систему.  Например, у тебя не отключены exception, потому надо поставить блок на них. Это делается так
```cpp
#include "NeuralNetwork.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-04-22 12:59 UTC, kifbell commented on Layer.h
> +    virtual Eigen::VectorXd passForward(const Eigen::VectorXd &input) = 0;
а что это за хедер должен быть, какой-то отдельный и любой существующий?

2024-04-22 13:01 UTC, kifbell commented on Layer.h
>  private:
а как я тогда буду их менять ?

2024-04-22 13:02 UTC, kifbell commented on Layer.h
> +    ReLULayer(int size)
что это значит ?

2024-04-22 13:27 UTC, kifbell commented on Optimizer.cpp
>      if (optimizerState.find("velocityWeights") == optimizerState.end())
это правильная идея, но я ее оставлю на потом :)

2024-04-22 13:44 UTC, kifbell commented on SoftmaxLayer.h
> +    Eigen::VectorXd lastOutput;
а если мне он нужен во время backprop, мне просто пересчитать его еще раз ?

2024-04-22 13:54 UTC, kifbell commented on SoftmaxLayer.h
> +    optimizer; // Suppress unused variable warning if not used
как я мог это знать просто ?:)

2024-04-22 14:33 UTC, kifbell commented on main.cpp
>  class MSELoss
честно, я не понял

2024-04-23 13:09 UTC, kifbell commented on Layer.h
> +    virtual Eigen::VectorXd passForward(const Eigen::VectorXd &input) = 0;
поправил, но вопрос актуален

2024-04-23 13:10 UTC, kifbell commented on Layer.h
>  private:
я так понял, что если я передаю приватный объект в функцию по ссылке , я смогу его менять потом

2024-06-07 18:31 UTC, merged